import { createFileRoute } from '@tanstack/react-router';
import { useState, useRef } from 'react';
import { MessageCircle, ClipboardList, Package, Map, UserRound, LogOut, ChevronDown, ChevronRight, ArrowLeft, ArrowRight, Plus, Eye, FileText, Layers, CalendarDays, GripVertical, MoreHorizontal, Check, Store, Search, Bell, ImagePlus, Settings2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { GroupEditor } from '@/components/group-editor';
import { CustomerPreview } from '@/components/customer-preview';
import { days, initialGroups, money, type OptionGroup, type Product } from '@/lib/menu-demo';
import plate from '@/assets/prato.jpg';
export const Route=createFileRoute('/')({head:()=>({meta:[{title:'Editar produto — Mesa'},{name:'description',content:'Gerencie produtos, opções de personalização e programação semanal do seu cardápio no Mesa.'},{property:'og:title',content:'Produtos e cardápio — Mesa'},{property:'og:description',content:'Cadastro de produtos e personalização de opções para cada dia da semana.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Index});
const initialProduct:Product={name:'Monte seu prato',description:'Escolha o tamanho, as guarnições e a carne do seu jeito.',price:'24,90',category:'Monte seu prato',available:true,image:plate};
function Index(){
 const [product,setProduct]=useState<Product>(initialProduct); const [saved,setSaved]=useState<Product>(initialProduct); const [groups,setGroups]=useState<OptionGroup[]>(initialGroups); const [savedGroups,setSavedGroups]=useState<OptionGroup[]>(initialGroups);
 const [group,setGroup]=useState<OptionGroup|null>(null); const [preview,setPreview]=useState(false); const [catalog,setCatalog]=useState(false); const [toast,setToast]=useState(''); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('Todos'); const [menu,setMenu]=useState<string|null>(null); const [remove,setRemove]=useState<string|null>(null); const [error,setError]=useState(''); const [isNew,setIsNew]=useState(false); const [hasProduct,setHasProduct]=useState(true); const fileRef=useRef<HTMLInputElement>(null);
 const notify=(text:string)=>{setToast(text);setTimeout(()=>setToast(''),3200);};
 const change=(values:Partial<Product>)=>setProduct(p=>({...p,...values}));
 const save=()=>{if(!product.name.trim()||!Number.isFinite(Number(product.price.replace(',','.')))||Number(product.price.replace(',','.'))<0){setError('Preencha o nome e um preço válido.');return;}setSaved({...product});setSavedGroups(structuredClone(groups));setHasProduct(true);setIsNew(false);setError('');notify('Produto salvo com sucesso');};
 const addGroup=()=>setGroup({id:crypto.randomUUID(),name:'',instruction:'',min:0,max:1,weekly:false,initialized:false,options:[]});
 const cancel=()=>{setProduct({...saved});setGroups(structuredClone(savedGroups));setCatalog(true);setIsNew(false);setError('');};
 return <div><aside className="app-sidebar"><div className="brand-mark" title="Mesa"><MessageCircle size={23}/></div>{[{icon:MessageCircle,label:'Conversas'},{icon:ClipboardList,label:'Pedidos'},{icon:Package,label:'Produtos'},{icon:Map,label:'Logística'},{icon:UserRound,label:'Perfil'}].map(({icon:Icon,label})=><Button key={label} variant="ghost" className={`sidebar-item ${label==='Produtos'?'active':''}`} onClick={()=>label==='Produtos'?setCatalog(true):notify(`${label} não faz parte desta demonstração`)}><Icon/><span>{label}</span></Button>)}<div className="sidebar-bottom"><div className="store-avatar" title="Pizzaria Isaque">PI</div><Button variant="ghost" size="icon" title="Sair" aria-label="Sair" className="text-muted-foreground" onClick={()=>notify('Esta demonstração não possui uma sessão de acesso')}><LogOut size={18}/></Button></div></aside>
 <div className="app-main"><header className="topbar"><div className="flex items-center gap-3"><Store size={19} className="text-muted-foreground"/><span className="font-semibold text-sm">Pizzaria Isaque</span><ChevronDown size={14} className="text-muted-foreground"/></div><div className="flex gap-5 items-center"><span className="pill green store-details"><span className="status-dot"/> Loja aberta</span><Button variant="ghost" size="icon" title="Notificações" aria-label="Notificações" className="text-muted-foreground" onClick={()=>notify('Nenhuma notificação por enquanto')}><Bell size={18}/></Button><div className="store-avatar">J</div></div></header>
 <main className="workspace"><div className="breadcrumb"><span>Cardápio</span><ChevronRight size={12}/><Button variant="link" className="h-auto p-0 text-xs text-muted-foreground" onClick={()=>setCatalog(true)}>Produtos</Button>{!catalog&&<><ChevronRight size={12}/><span className="text-foreground">{isNew?'Novo produto':'Editar produto'}</span></>}</div>
 <div className="page-heading"><div><h1 className="page-title">{catalog?'Produtos':isNew?'Novo produto':'Editar produto'}</h1><p className="page-subtitle">{catalog?'Seu cardápio, organizado do seu jeito.':'Detalhes e opções que fazem parte do seu produto.'}</p></div><div className="heading-actions flex gap-2">{catalog?<Button onClick={()=>{setIsNew(true);setProduct({name:'',description:'',price:'0,00',category:'Pratos',available:true,image:plate});setGroups([]);setCatalog(false);}}><Plus/> Novo produto</Button>:<><Button variant="outline" onClick={()=>setPreview(true)}><Eye/> Prévia</Button><Button variant="outline" onClick={()=>setCatalog(true)}><ArrowLeft/> Catálogo</Button></>}</div></div>
 {catalog?<><div className="flex gap-3 flex-wrap"><div className="relative flex-1 min-w-48"><Search className="absolute left-3 top-3 text-muted-foreground" size={16}/><input aria-label="Buscar produtos" placeholder="Buscar produto..." className="pl-10" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filtrar disponibilidade" className="w-auto" value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option>Disponíveis</option><option>Indisponíveis</option></select></div><div className="catalog-grid">{hasProduct&&saved.name.toLowerCase().includes(query.toLowerCase())&&(filter==='Todos'||(filter==='Disponíveis'&&saved.available)||(filter==='Indisponíveis'&&!saved.available))?<article className="surface catalog-card"><img src={saved.image} alt={saved.name} width={1024} height={1024}/><div className="catalog-card-body"><span className={`pill ${saved.available?'green':'amber'}`}>{saved.available?'Disponível':'Indisponível'}</span><h2 className="font-semibold text-lg mt-3">{saved.name}</h2><p className="preview-description mt-2">{saved.description}</p><div className="flex items-center justify-between mt-5"><strong>{money(Number(saved.price.replace(',','.')))}</strong><Button variant="outline" size="sm" onClick={()=>{setProduct({...saved});setGroups(structuredClone(savedGroups));setCatalog(false);setIsNew(false);}}><Settings2/> Editar</Button></div></div></article>:<p className="text-muted-foreground py-8">Nenhum produto encontrado.</p>}</div></>:<>
 <div className="editor-grid"><div><section className="surface form-panel"><h2 className="section-heading"><FileText className="section-icon"/> Informações do produto</h2><div className="fields"><div className="field"><label htmlFor="product-name">Nome do produto <span className="text-primary">*</span></label><input id="product-name" placeholder="Nome do produto" value={product.name} onChange={e=>change({name:e.target.value})}/></div><div className="field"><label htmlFor="description">Descrição</label><textarea id="description" rows={3} value={product.description} placeholder="Descreva seu produto" onChange={e=>change({description:e.target.value})}/><span className="field-hint">O que o cliente lê antes de fazer o pedido.</span></div><div className="two-cols"><div className="field"><label htmlFor="price">Preço base (R$) <span className="text-primary">*</span></label><input id="price" inputMode="decimal" value={product.price} onChange={e=>change({price:e.target.value})}/></div><div className="field"><label htmlFor="availability">Disponibilidade</label><select id="availability" value={product.available?'yes':'no'} onChange={e=>change({available:e.target.value==='yes'})}><option value="yes">Disponível</option><option value="no">Indisponível</option></select></div></div><div className="field"><label htmlFor="category">Categoria</label><select id="category" value={product.category} onChange={e=>change({category:e.target.value})}><option>Monte seu prato</option><option>Pratos</option><option>Pizzas</option><option>Bebidas</option><option>Sobremesas</option></select></div><div className="field"><label>Imagem do produto</label><div className="image-upload"><img src={product.image} alt="Foto do produto" width={1024} height={1024}/><div><Button variant="outline" size="sm" onClick={()=>fileRef.current?.click()}><ImagePlus/> Alterar imagem</Button><p className="field-hint mt-2">JPG, PNG ou WebP. Até 8 MB.</p></div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024)return notify('A imagem deve ter até 8 MB');if(!['image/jpeg','image/png','image/webp'].includes(f.type))return notify('Escolha uma imagem JPG, PNG ou WebP');change({image:URL.createObjectURL(f)});}}/></div></div></div></section>
 <section className="group-section"><div className="flex justify-between items-center gap-3"><h2 className="section-heading"><Layers className="section-icon"/> Grupos de opções</h2><span className="pill">{groups.length} grupos</span></div><p className="page-subtitle text-xs mt-2">Personalizações que o cliente pode escolher ao pedir.</p>{groups.map((g,i)=><article className="surface group-card" key={g.id}><div className="group-symbol"><Layers size={18}/></div><Button variant="ghost" className="group-title" onClick={()=>setGroup(g)}><strong>{g.name}</strong><p>{g.max===1?'Escolha única':`Até ${g.max} escolhas`} · {g.min>0?'Obrigatório':'Opcional'}</p><div className="flex gap-5 mt-1"><span className="text-muted-foreground text-[10px]">{g.options.length} opções</span>{g.weekly&&<span className="pill green"><CalendarDays size={10}/> Semanal</span>}</div></Button><Button variant="ghost" size="icon" className="text-muted-foreground h-7 w-7" title="Editar grupo" aria-label={`Editar ${g.name}`} onClick={()=>setGroup(g)}><ArrowRight size={16}/></Button><div className="relative"><Button variant="ghost" size="icon" className="text-muted-foreground h-7 w-7" title="Mais ações" aria-label={`Ações de ${g.name}`} onClick={()=>setMenu(menu===g.id?null:g.id)}><MoreHorizontal/></Button>{menu===g.id&&<div className="absolute right-0 top-9 z-30 bg-card border border-border rounded-md shadow-lg p-1 w-40"><Button variant="ghost" size="sm" className="w-full justify-start" disabled={i===0} onClick={()=>{setGroups(gs=>{const next=[...gs];[next[i-1],next[i]]=[next[i],next[i-1]];return next;});setMenu(null);}}><GripVertical/> Mover para cima</Button><Button variant="ghost" size="sm" className="w-full justify-start text-destructive" onClick={()=>{setRemove(g.id);setMenu(null);}}>Excluir grupo</Button></div>}</div></article>)}<Button variant="outline" className="w-full mt-3 border-dashed h-11 text-primary" onClick={addGroup}><Plus/> Adicionar grupo de opções</Button></section>
 </div><aside className="preview-column"><p className="preview-label">No cardápio do cliente</p><article className="surface"><img src={product.image} alt="Prato de arroz, feijão, frango e salada" className="preview-photo" width={1024} height={1024}/><div className="preview-body"><span className={`pill ${product.available?'green':'amber'}`}>{product.available?<><span className="status-dot"/> Disponível</>:'Indisponível'}</span><h3>{product.name||'Nome do produto'}</h3><p className="preview-description">{product.description||'Descrição do produto'}</p><p className="preview-price">{money(Number(product.price.replace(',','.'))||0)}</p><div className="preview-summary">{groups.map(g=><div className="summary-row" key={g.id}><span>{g.name}</span><span className="text-muted-foreground">{g.min>0?'Obrigatório':'Opcional'}</span></div>)}</div><Button variant="outline" className="w-full text-xs" onClick={()=>setPreview(true)}><Eye/> Ver como cliente</Button></div></article><section className="week-info"><h3 className="flex items-center gap-2 font-medium text-xs"><CalendarDays size={15} className="text-primary"/> Um produto, diferentes dias</h3><p>{groups.filter(g=>g.weekly).length} grupos com programação semanal.</p><div className="day-dots">{days.map(d=><span className="day-dot flex items-center justify-center bg-accent text-primary" key={d}>{d.slice(0,1)}</span>)}</div></section></aside></div>
 {error&&<p role="alert" className="text-destructive text-xs mt-4">{error}</p>}<footer className="action-bar"><span className="saved-note"><Check size={13}/> {JSON.stringify(product)===JSON.stringify(saved)&&JSON.stringify(groups)===JSON.stringify(savedGroups)?'Todas as alterações salvas':'Alterações ainda não salvas'}</span><div className="flex gap-2"><Button variant="outline" onClick={cancel}>Cancelar</Button><Button onClick={save}><Check/> Salvar produto</Button></div></footer></>}
 <div className="flex justify-between text-muted-foreground text-[10px] mt-8 pt-5 border-t border-border"><span className="font-semibold flex gap-1 items-center"><MessageCircle size={12}/> mesa</span><span>Gestão de cardápio</span></div>
 </main></div>{group&&<GroupEditor key={group.id} group={group} onClose={()=>setGroup(null)} onSave={g=>{setGroups(gs=>gs.some(x=>x.id===g.id)?gs.map(x=>x.id===g.id?g:x):[...gs,g]);setGroup(null);notify('Grupo atualizado');}} onDelete={()=>setRemove(group.id)}/>} {preview&&<CustomerPreview product={product} groups={groups} onClose={()=>setPreview(false)}/>}
 <Dialog open={!!remove} onOpenChange={open=>!open&&setRemove(null)}><DialogContent><DialogTitle>Excluir grupo de opções?</DialogTitle><DialogDescription>O grupo e suas opções serão removidos deste produto, incluindo a programação semanal.</DialogDescription><div className="flex justify-end gap-2 mt-3"><Button variant="outline" onClick={()=>setRemove(null)}>Cancelar</Button><Button variant="destructive" onClick={()=>{setGroups(gs=>gs.filter(g=>g.id!==remove));setRemove(null);setGroup(null);notify('Grupo excluído');}}>Excluir grupo</Button></div></DialogContent></Dialog>
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}</div>;
}
