import { useState } from 'react';
import { ShoppingBag, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { days, money, type Product, type OptionGroup } from '@/lib/menu-demo';
export function CustomerPreview({product, groups, onClose}: {product:Product;groups:OptionGroup[];onClose:()=>void}) {
 const [day,setDay]=useState(0); const [choices,setChoices]=useState<Record<string,string[]>>({}); const [added,setAdded]=useState(false);
 const available=(g:OptionGroup)=>g.options.filter(o=>o.available&&(!g.weekly||o.days.includes(day)));
 const valid=product.available&&groups.every(g=>(choices[g.id]?.length||0)>=g.min && available(g).length>=g.min);
 const total=Number(product.price.replace(',','.'))+groups.reduce((sum,g)=>sum+g.options.filter(o=>choices[g.id]?.includes(o.id)).reduce((s,o)=>s+o.price,0),0);
 const toggle=(g:OptionGroup,id:string)=>{setAdded(false);setChoices(c=>{const selected=c[g.id]||[];return {...c,[g.id]:selected.includes(id)?selected.filter(x=>x!==id):g.max===1?[id]:selected.length<g.max?[...selected,id]:selected};});};
 return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="customer-modal modal-content"><div><DialogTitle>Prévia do cardápio</DialogTitle><DialogDescription className="mt-2">{days[day]} · Opções disponíveis para o cliente</DialogDescription></div><div className="field"><label htmlFor="preview-day">Dia da semana</label><select id="preview-day" value={day} onChange={e=>{setDay(Number(e.target.value));setChoices({});setAdded(false);}}>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></div><img src={product.image} alt={product.name} className="w-full aspect-[2.4] object-cover rounded-md" width={1024} height={1024}/><div><h2 className="text-xl font-semibold">{product.name}</h2><p className="preview-description mt-2">{product.description}</p><p className="font-semibold mt-2">{money(Number(product.price.replace(',','.')))}</p></div>{groups.map(g=><section key={g.id} className="border-t border-border pt-4"><div className="flex items-center justify-between gap-2"><h3 className="font-semibold text-sm">{g.name}</h3><span className={`pill ${g.min>0?'green':''}`}>{g.min>0?'Obrigatório':'Opcional'} · até {g.max}</span></div><p className="field-hint mt-1">{g.instruction}</p>{available(g).map(o=><label className="customer-option" key={o.id}><span className="flex gap-3 items-center"><input type="checkbox" checked={choices[g.id]?.includes(o.id)||false} disabled={!choices[g.id]?.includes(o.id)&&g.max>1&&(choices[g.id]?.length||0)>=g.max} onChange={()=>toggle(g,o.id)}/>{o.name}</span><span className="text-muted-foreground">{o.price?`+ ${money(o.price)}`:'Incluso'}</span></label>)}{available(g).length===0&&<p className="field-hint py-4">Nenhuma opção disponível neste dia.</p>}</section>)}<Button className="w-full h-11 justify-between" disabled={!valid} onClick={()=>setAdded(true)}><span className="flex items-center gap-2">{added?<Check/>:<ShoppingBag/>}{added?'Adicionado ao pedido':'Adicionar ao pedido'}</span><span>{money(total)}</span></Button>{!valid&&<p className="field-hint text-center">{!product.available?'Produto indisponível.':'Selecione as opções obrigatórias para continuar.'}</p>}</DialogContent></Dialog>;
}
